### ISSUE TITLE
Using nullable arguments with a null value has no effect

### ISSUE THREAD

**Issue by bastones** [goldspecdigital/voodoo-sms-sdk#2]
https://github.com/goldspecdigital/voodoo-sms-sdk/blob/13140b94d70ea53cec4f268609f8ba83d6035709/src/Client.php#L73

Using nullable types with a default value of null such as `?string $from = null` has no effect. A type-hinted parameter is implicitly nullable if a null value is provided as the default.

In this case, the only practical difference between the use of nullable types, and typehinting with a default value of `null`, is the ability to enforce the calling code to pass an accepted value rather than the default value being implicit if no value is passed. This means a default value of `null` on a nullable type has no effect.

**Comment by matthew-inamdar** [comment]
Good idea. I suppose it makes the code more complex than it needs to be and suggests that the client could pass in `null` even though they never would need to...

Fixed in #3 

Closing.
